---
sidebar: sidebar 
permalink: concept-write-speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: Cloud Manager 可讓您選擇一般或高速寫入速度 Cloud Volumes ONTAP 來執行功能。在您選擇寫入速度之前、您應該先瞭解一般與高設定之間的差異、以及使用高速寫入速度時的風險與建議。 
---
= 寫入速度
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Manager 可讓您選擇一般或高速寫入速度 Cloud Volumes ONTAP 來執行功能。在您選擇寫入速度之前、您應該先瞭解一般與高設定之間的差異、以及使用高速寫入速度時的風險與建議。

所有類型的單一節點系統均支援高速寫入。使用特定執行個體或 VM 類型時、 AWS 和 Azure 中的 HA 配對也支援此功能（請參閱下列各節以取得支援執行個體和 VM 類型的清單）。GCP 中的 HA 配對不支援高速寫入速度。



== 正常寫入速度

當您選擇正常寫入速度時、資料會直接寫入磁碟。當資料直接寫入磁碟時、可降低發生非計畫性系統中斷或因非計畫性系統中斷而發生串聯故障的資料遺失可能性（僅限 HA 配對）。

正常寫入速度為預設選項。



== 高速寫入

選擇高速寫入速度時、資料會在寫入磁碟之前先緩衝到記憶體中、以提供更快的寫入效能。由於這種快取、如果發生非計畫性的系統中斷、可能會導致資料遺失。

發生非計畫性系統中斷時可能遺失的資料量、是最後兩個一致點的範圍。一致點是將緩衝資料寫入磁碟的行為。寫入日誌已滿或 10 秒後（以先到者為準）、就會出現一致點。不過、雲端供應商所提供的儲存設備效能、可能會影響一致點處理時間。



=== 何時使用高速寫入

如果您的工作負載需要快速寫入效能、而且在發生非計畫性系統中斷或發生非計畫性系統中斷的串聯故障時、您可以承受資料遺失的風險（僅限 HA 配對）、那麼高速寫入速度是很好的選擇。



=== 使用高速寫入速度時的建議事項

如果您啟用高速寫入速度、則應確保應用程式層的寫入保護、或是應用程式在發生資料遺失時仍能承受。



=== 使用AWS中的HA配對來高速寫入

如果您計畫在AWS中啟用HA配對的高速寫入速度、您應該瞭解多個可用度區域（AZ）部署與單一AZ部署之間的保護層級差異。在多個AZs之間部署HA配對可提供更多恢復能力、並有助於降低資料遺失的機率。

link:concept-ha.html["深入瞭解AWS中的HA配對"]。



=== 支援高速寫入的組態

並非所有 Cloud Volumes ONTAP 的不支援高速寫入的組態。這些組態預設會使用正常寫入速度。



==== AWS

如果您使用單一節點系統、 Cloud Volumes ONTAP 則支援所有執行個體類型的高速寫入速度。

從9.8版開始、Cloud Volumes ONTAP 當使用幾乎所有支援的EC2執行個體類型（m5.xlarge和r5.xlarge除外）時、支援HA配對的高速寫入速度。

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["深入瞭解Cloud Volumes ONTAP 支援的Amazon EC2執行個體"^]。



==== Azure

如果您使用單一節點系統、 Cloud Volumes ONTAP 則支援所有 VM 類型的高速寫入速度。

如果您使用HA配對、Cloud Volumes ONTAP 從9.8版開始、支援多種VM類型的高速寫入速度。前往 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["發行說明 Cloud Volumes ONTAP"^] 可查看支持高速寫入速度的VM類型。



==== Google Cloud

如果您使用單一節點系統、 Cloud Volumes ONTAP 則支援所有機器類型的高速寫入速度。

在 Google Cloud 中、使用 HA 配對不支援高速寫入。 Cloud Volumes ONTAP

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["深入瞭解Cloud Volumes ONTAP 支援的Google Cloud機器類型"^]。



== 如何選擇寫入速度

您可以在建立新的工作環境時選擇寫入速度、而且可以 link:task-modify-write-speed.html["變更現有系統的寫入速度"]。



== 發生資料遺失時的預期結果

如果您選擇高速寫入速度且發生資料遺失、則系統應能在不需使用者介入的情況下開機並繼續提供資料。當節點發生資料遺失時、會報告兩則 EMS 訊息。其中一個是 wafl.root.content.changed 、其中一個是錯誤嚴重性層級事件、另一個是 nv.check.failed 、其中包含偵錯嚴重性層級事件。這兩個訊息都必須顯示為資料遺失的指示。



== 如何在資料遺失時停止資料存取

如果您擔心資料遺失、希望應用程式在資料遺失時停止執行、並在資料遺失問題妥善解決後恢復資料存取、您可以從 CLI 使用 NVFIL 選項來達成此目標。

啟用 NVFIL 選項:: 「 vol modify -volume <vol-name> -nv故障 開啟」
檢查 NVFIL 設定:: 「 vol show -volume <vol-name> -功能 變數 nv失敗 」
停用 NVFIL 選項:: 「 volvol modify -volume <vol-name> -nvail off' 」


發生資料遺失時、啟用 NVFIL 的 NFS 或 iSCSI 磁碟區應停止提供資料（不影響無狀態傳輸協定的 CIFS ）。如需詳細資料、請參閱 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["NVFIL 如何影響 NFS 磁碟區或 LUN 的存取"^]。

以檢查 NVFIL 狀態:: 「 vol show -功能 變數 in -nvfaile-state 」


正確解決資料遺失問題之後、您可以清除 NVFIL 狀態、磁碟區將可供資料存取。

清除 NVFIL 狀態:: 「 vol modify -volume <vol-name> -in nvfaile-state 假」

