---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, flexgroup, ontap s3, s3 configuration, svm dr, svm disaster recovery, disaster recovery, storage vm dr 
summary: 已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。 
---
= 已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制指出本產品版本不支援的平台、裝置或功能、或是無法與產品正確互通的平台、裝置或功能。請仔細檢閱這些限制。

這些限制僅適用於Cloud Volumes ONTAP Cloud Manager的內部資料管理。若要檢視Cloud Volumes ONTAP 有關此功能的限制、 https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limitations.html["前往Cloud Volumes ONTAP 《發行說明》"^]



== Cloud Manager 不支援 FlexGroup 支援

雖然支援不支援任何功能、但 Cloud Manager 卻不支援。 Cloud Volumes ONTAP FlexGroup如果 FlexGroup 您從 System Manager 或 CLI 建立一個支援功能區、則應將 Cloud Manager 的容量管理模式設為手動。自動模式可能無法與 FlexGroup 功能不全的功能搭配使用。



== Cloud Manager Cloud Volumes ONTAP 不支援S3搭配使用

雖然在某些雲端供應商中、支援S3作為橫向擴充儲存設備的選項、但Cloud Manager並未針對此功能提供任何管理功能。Cloud Volumes ONTAP使用CLI是設定S3用戶端從Cloud Volumes ONTAP 功能支援的最佳實務做法。如需詳細資訊、請參閱 http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-s3-cg/home.html["S3組態電源指南"^]。

link:concept-client-protocols.html["深入瞭Cloud Volumes ONTAP 解支援S3和其他用戶端傳輸協定的功能"]。



== Cloud Manager不支援儲存VM的災難恢復

Cloud Manager 不提供任何儲存 VM 災難恢復的設定或協調支援。您必須使用 System Manager 或 CLI 。

* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["SVM 災難恢復準備快速指南"^]
* https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["SVM Disaster Recovery Express 指南"^]

