---
sidebar: sidebar 
permalink: reference-default-configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: 瞭解 Cloud Volumes ONTAP 根據預設設定的功能可協助您設定及管理系統、尤其是熟悉 ONTAP 使用功能時、因為 Cloud Volumes ONTAP 預設的功能與 ONTAP 使用功能不相同、所以使用功能不一。 
---
= 的預設組態 Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
瞭解 Cloud Volumes ONTAP 根據預設設定的功能可協助您設定及管理系統、尤其是熟悉 ONTAP 使用功能時、因為 Cloud Volumes ONTAP 預設的功能與 ONTAP 使用功能不相同、所以使用功能不一。



== 預設值

* 可在 AWS 、 Azure 和 GCP 中以單節點系統和 HA 配對的形式使用。 Cloud Volumes ONTAP
* Cloud Manager 部署 Cloud Volumes ONTAP 時會建立一個資料服務儲存 VM 、部分組態支援額外的儲存 VM 。 link:task-managing-svms.html["深入瞭解管理儲存 VM"]。
+
從Cloud Manager 3.9.5版本開始、系統會在初始儲存VM上啟用邏輯空間報告功能。以邏輯方式回報空間時ONTAP 、此功能會報告磁碟區空間、讓儲存效率功能所節省的所有實體空間也會報告為已使用。

* Cloud Manager 會自動在 ONTAP 下列功能授權上安裝 Cloud Volumes ONTAP 於更新：
+
** CIFS
** FlexCache
** FlexClone
** iSCSI
** NetApp Volume Encryption （僅適用於 BYOL 或註冊的 PAYGO 系統）
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* 預設會建立多個網路介面：
+
** 叢集管理 LIF
** 叢集間 LIF
** Azure 和 GCP 中 HA 系統上的 SVM 管理 LIF 、 AWS 中的單一節點系統上的 SVM 管理 LIF 、以及多個 AWS 可用性區域中的 HA 系統上的 SVM 管理 LIF （可選）
** 節點管理LIF（在GCP中、此LIF與叢集間LIF結合使用）
** iSCSI 資料 LIF
** CIFS 與 NFS 資料 LIF
+

NOTE: 由於 Cloud Volumes ONTAP EC2 需求、 LIF 容錯移轉功能預設為停用。將 LIF 移轉至其他連接埠會中斷執行個體上 IP 位址與網路介面的外部對應、使 LIF 無法存取。



* 使用 HTTPS 將組態備份傳送至 Connector 。 Cloud Volumes ONTAP
+
可從存取備份 https://ipaddress/occm/offboxconfig/[] 其中 _ipaddress_ 是連接器主機的 IP 位址。

* Cloud Manager 設定的磁碟區屬性與其他管理工具（例如 System Manager 或 CLI ）有所不同。
+
下表列出 Cloud Manager 設定的 Volume 屬性與預設值不同：

+
[cols="15,85"]
|===
| 屬性 | Cloud Manager 設定的價值 


| 自動調整大小模式 | 成長 


| 最大自動調整大小  a| 
1 、 000 %


NOTE: 帳戶管理員可從「設定」頁面修改此值。



| 安全風格 | 適用於 CIFS Volume UNIX for NFS Volume 的 NTFS 


| 空間保證風格 | 無 


| UNIX 權限（僅限 NFS ） | 777 
|===
+
有關這些屬性的信息，請參見 _volume creation_ 手冊頁。





== 用於系統資料的內部磁碟

除了使用者資料的儲存設備、 Cloud Manager 也購買雲端儲存設備來儲存系統資料。



=== AWS

* 每個節點有三個磁碟用於開機、根和核心資料：
+
** 45 GB IO1磁碟用於開機資料
** 140 GiB GP3磁碟用於根資料
** 540 GiB gp2磁碟用於核心資料


* 每個開機磁碟和根磁碟各一份 EBS 快照
* 對於HA配對、一個EBS Volume用於「內化器」執行個體、約為8 GiB



TIP: 在AWS中、NVRAM位於開機磁碟上。



=== Azure （單一節點）

* 三個優質 SSD 磁碟：
+
** 一個10 GiB磁碟用於開機資料
** 一個140 GiB磁碟用於根資料
** 一個512 GiB磁碟用於NVRAM
+
如果您選擇Cloud Volumes ONTAP 的虛擬機器支援Ultra SSD、則系統會使用32 GiB Ultra SSD來執行NVRAM、而非使用Premium SSD。



* 一張1024 GiB標準HDD磁碟、可節省核心
* 每個開機磁碟和根磁碟各一份 Azure 快照




=== Azure（HA配對）

* 兩個10 GiB Premium SSD磁碟用於開機磁碟區（每個節點一個）
* 兩個140 GiB Premium Storage頁面、用於根磁碟區（每個節點一個）
* 兩個1024 GiB標準HDD磁碟、可節省核心（每個節點一個）
* 兩個512 GiB Premium SSD磁碟用於NVRAM（每個節點一個）
* 每個開機磁碟和根磁碟各一份 Azure 快照




=== Google Cloud（單一節點）

* 一個10 GiB SSD持續磁碟用於開機資料
* 一個64 GiB SSD持續磁碟用於根資料
* 一個500 GiB SSD持續磁碟用於NVRAM
* 一個315 GiB標準持續磁碟、用於儲存核心
* 用於開機和根資料的快照




=== Google Cloud（HA配對）

* 兩個10 GiB SSD持續磁碟、用於開機資料
* 四個64 GiB SSD持續磁碟用於根資料
* 兩個500 GiB SSD持續磁碟用於NVRAM
* 兩個315 GiB標準持續磁碟、用於儲存核心
* 一個10 GiB標準持續磁碟、用於中介資料
* 用於開機和根資料的快照




=== 磁碟所在位置

Cloud Manager 的儲存設備如下所示：

* 開機資料位於附加至執行個體或虛擬機器的磁碟上。
+
此磁碟包含開機映像、 Cloud Volumes ONTAP 不適用於 Image.

* 根資料包含系統組態和記錄檔、位於 aggr0 中。
* 儲存虛擬機器（ SVM ）根磁碟區位於 aggr1 中。
* 資料磁碟區也位於 aggr1 中。




=== 加密

Azure 和 Google Cloud Platform 會一律加密開機和根磁碟、因為這些雲端供應商預設會啟用加密功能。

當您使用金鑰管理服務（ KMS ）在 AWS 中啟用資料加密時、 Cloud Volumes ONTAP 也會加密適用於此功能的開機磁碟和根磁碟。這包括 HA 配對中中介執行個體的開機磁碟。磁碟會使用您在建立工作環境時所選取的 CMK 進行加密。
